version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build: .
    depends_on:
      - db
    command: ["pytest", "test_db.py"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge